"""Initial migration

Revision ID: 11fdd66fc20e
Revises: 
Create Date: 2020-08-22 01:56:38.326182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fdd66fc20e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('fase', sa.String(length=64), nullable=True),
    sa.Column('contenido', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('autos_numero', sa.Integer(), nullable=True),
    sa.Column('autos_ano', sa.Integer(), nullable=True),
    sa.Column('juzgado', sa.String(length=256), nullable=True),
    sa.Column('clientes', sa.Integer(), nullable=True),
    sa.Column('fase', sa.Integer(), nullable=True),
    sa.Column('cuantia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_tokens_target_name'), 'registration_tokens', ['target_name'], unique=True)
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('alias', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('nombre', sa.String(length=24), nullable=True),
    sa.Column('apellidos', sa.String(length=48), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('registration_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registration_token_id'], ['registration_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_alias'), 'user', ['alias'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.Integer(), nullable=True),
    sa.Column('actuacion', sa.Integer(), nullable=True),
    sa.Column('visibilidad', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=12), nullable=True),
    sa.Column('contenido', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['actuacion'], ['actuacion.id'], ),
    sa.ForeignKeyConstraint(['autor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('evento')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_alias'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.drop_index(op.f('ix_registration_tokens_target_name'), table_name='registration_tokens')
    op.drop_table('registration_tokens')
    op.drop_table('expediente')
    op.drop_table('actuacion')
    # ### end Alembic commands ###
